import { Item } from './../entities/item';

export const ITEMS: Item[] = [
  { id: 1, name: 'Mr. Nice' },
  { id: 2, name: 'Narco' },
  { id: 3, name: 'Bombasto' },
  { id: 4, name: 'Celeritas' },
  { id: 5, name: 'Magneta' },
  { id: 6, name: 'RubberMan' },
  { id: 7, name: 'Dynama' },
  { id: 8, name: 'Dr IQ' },
  { id: 9, name: 'Magma' },
  { id: 10, name: 'Tornado' },
  { id: 11, name: 'Mr. Nice' },
  { id: 12, name: 'Narco' },
  { id: 13, name: 'Bombasto' },
  { id: 14, name: 'Celeritas' },
  { id: 15, name: 'Magneta' },
  { id: 16, name: 'RubberMan' },
  { id: 17, name: 'Dynama' },
  { id: 18, name: 'Dr IQ' },
  { id: 19, name: 'Magma' },
  { id: 20, name: 'Tornado' },
  { id: 21, name: 'Mr. Nice' },
  { id: 22, name: 'Narco' },
  { id: 23, name: 'Bombasto' },
  { id: 24, name: 'Celeritas' },
  { id: 25, name: 'Magneta' },
  { id: 26, name: 'RubberMan' },
  { id: 27, name: 'Dynama' },
  { id: 28, name: 'Dr IQ' },
  { id: 29, name: 'Magma' },
  { id: 30, name: 'Tornado' },
];
